#!/usr/bin/env bash
set -euo pipefail

# Generates one OpenCode slash-command stub per skill in this repo (excluding
# deprecated/), so `/<skill-name>` works in OpenCode the way it does in Claude
# Code.
#
# OpenCode already discovers the skills themselves — it globs
# ~/.claude/skills/**/SKILL.md and ~/.agents/skills/**/SKILL.md (both populated
# by link-skills.sh) and follows symlinks. What it does NOT do is read
# ~/.claude/commands: its "/" palette is built only from {command,commands}/**/*.md
# under its own config dir. Without these stubs a user-invoked skill
# (disable-model-invocation: true) is unreachable in OpenCode entirely, not
# merely unlisted.
#
# Each stub is a pointer, not a copy of the skill: it tells the agent to read the
# SKILL.md at its absolute path and to resolve relative paths against the skill's
# own directory. Symlinking the SKILL.md instead would inline its body as the
# prompt template and strip that directory context, dangling every references/…
# path the skill depends on.
#
# Idempotent. Re-run after adding, renaming, or removing a skill.

REPO="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="${OPENCODE_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/opencode}"
COMMAND_DIR="$CONFIG_DIR/command"

# Stamped into every generated file so pruning only ever deletes our own stubs
# and leaves hand-written commands alone.
MARKER="<!-- generated by link-opencode-commands.sh -->"

if ! command -v opencode >/dev/null 2>&1 \
  && [ ! -x "$HOME/.opencode/bin/opencode" ] \
  && [ ! -d "$CONFIG_DIR" ]; then
  echo "opencode not installed — skipping command generation"
  exit 0
fi

# Prints a SKILL.md's frontmatter `description`, folded onto one line and escaped
# for use inside a double-quoted YAML scalar. Handles plain, quoted and block
# (| and >) scalars. OpenCode refuses to start if any command file has invalid
# frontmatter, so the output is always re-escaped rather than passed through.
skill_description() {
  awk '
    function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t\r]+$/, "", s); return s }
    BEGIN { bs = sprintf("%c", 92); dq = sprintf("%c", 34); sq = sprintf("%c", 39) }
    NR == 1 { if ($0 !~ /^---[ \t\r]*$/) exit; next }
    /^(---|\.\.\.)[ \t\r]*$/ { exit }
    !capturing && /^description:/ {
      val = trim(substr($0, 13))
      if (val ~ /^[|>][0-9+-]*$/) val = ""   # block scalar header; body follows
      capturing = 1
      next
    }
    capturing {
      # Continuation lines are indented (or blank); anything at column 0 is the
      # next key.
      if ($0 ~ /^[ \t]/ || trim($0) == "") {
        line = trim($0)
        if (line != "") val = (val == "" ? line : val " " line)
        next
      }
      capturing = 0
    }
    END {
      gsub(/[\t\r]/, " ", val)
      gsub(/ +/, " ", val)
      val = trim(val)

      n = length(val)
      if (n >= 2) {
        first = substr(val, 1, 1); last = substr(val, n, 1)
        if (first == dq && last == dq) {
          val = substr(val, 2, n - 2)
          gsub(bs bs dq, dq, val)
          gsub(bs bs bs bs, bs bs, val)
        } else if (first == sq && last == sq) {
          val = substr(val, 2, n - 2)
          gsub(sq sq, sq, val)
        }
      }

      # OpenCode truncates long palette entries anyway.
      if (length(val) > 200) val = trim(substr(val, 1, 197)) "..."

      out = ""
      for (i = 1; i <= length(val); i++) {
        c = substr(val, i, 1)
        if (c == bs || c == dq) out = out bs
        out = out c
      }
      print out
    }
  ' "$1"
}

render_stub() {
  local src="$1" desc="$2"
  cat <<EOF
---
description: "$desc"
---
$MARKER
Read \`$src/SKILL.md\` in full and follow it as your instructions for this task.

Resolve any relative paths it mentions against \`$src/\`.

The user's input, which may be empty:

\$ARGUMENTS
EOF
}

mkdir -p "$COMMAND_DIR"

WRITTEN=""
while IFS= read -r -d '' skill_md; do
  src="$(dirname "$skill_md")"
  name="$(basename "$src")"
  desc="$(skill_description "$skill_md")"
  [ -n "$desc" ] || desc="Run the $name skill."

  out="$COMMAND_DIR/$name.md"
  new="$(render_stub "$src" "$desc")"
  if [ ! -f "$out" ] || [ "$(cat "$out")" != "$new" ]; then
    printf '%s\n' "$new" > "$out"
    echo "wrote $name -> $src ($COMMAND_DIR)"
  fi
  WRITTEN="$WRITTEN$name"$'\n'
done < <(
  find "$REPO" -name SKILL.md \
    -not -path '*/node_modules/*' \
    -not -path '*/.git/*' \
    -not -path '*/deprecated/*' \
    -print0
)

for f in "$COMMAND_DIR"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .md)"
  if ! grep -qxF "$name" <<<"$WRITTEN"; then
    if grep -qF "$MARKER" "$f"; then
      rm "$f"
      echo "removed stale $name ($COMMAND_DIR)"
    fi
  fi
done
